### ISSUE TITLE
Why the scale of dbp15k here is different from that on the NJU website?

### ISSUE THREAD

**Issue by 1049451037** [nju-websoft/JAPE#2]
For example, there are about 20k English entities in fr_en here (data/dbp15k.tar.gz), but 100k on the [NJU website](http://ws.nju.edu.cn/jape/). Does it mean that you tested with some subsets of dbp15k? If so, how the subsets extracted?

**Comment by sunzequn** [comment]
The dataset in github is the input of JAPE model, while the dataset in our website is the full triples about the selected 15k entities. "15k" means the number of aligned entity pairs is 15k. We extracted the relation and attribute triples with these entities as head. Thus, there are many tail entities are not among our "15k" entities. This causes that there are about 100k entities in fr-en dataset. The statistics of our datasets were reported in Table 1.
The input of JAPE is a subset of the full datasets because some triples make little contribution to embedding-based entity alignment, such as the triples whose tail entities are not among “15k”. As we have explained “In our experiment, we do not use all the triples in datasets. For relationship triples, we select a portion whose head and tail entities are popular. For attribute triples, we discard their values due to diversity and cross-linguality.” 
Thus, you can test your model with the same input as JAPE, or using the full dataset with the same training and test reference alignment.

**Comment by 1049451037** [comment]
Got it. Thanks!
